on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Choose env"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "depoly"
